name: CD main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image (latest + SHA)
        run: |
          REPO_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/${REPO_LC}
          docker build -t ${IMAGE}:latest Project
          docker tag ${IMAGE}:latest ${IMAGE}:${GITHUB_SHA}
          docker push ${IMAGE}:latest
          docker push ${IMAGE}:${GITHUB_SHA}

      - name: Setup kubectl
        if: ${{ secrets.KUBECONFIG_B64 != '' }}
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.28.0'

      - name: Write kubeconfig from secret
        if: ${{ secrets.KUBECONFIG_B64 != '' }}
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_B64}" | base64 -d > $HOME/.kube/config
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}

      - name: Update K8s deployment to new image (pin SHA)
        if: ${{ secrets.KUBECONFIG_B64 != '' }}
        run: |
          REPO_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          kubectl -n prod set image deploy/fm-app app=ghcr.io/${REPO_LC}:${GITHUB_SHA}
          kubectl -n prod rollout status deploy/fm-app
