name: CI feature
on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.sha }}
          # change "Project" to "." if Dockerfile is at repo root
          docker build -t $IMAGE Project
          docker push $IMAGE
