name: CI feature
on:
  push:
    branches:
      - 'feature/**'
      - 'AWS-Code'
      - 'HTML-Setting'
      - 'Html-setting'
      - 'Web-Browser'
      - 'eks'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          REPO_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          IMAGE=ghcr.io/${REPO_LC}:${GITHUB_SHA}
          echo "Building image $IMAGE"

          docker build -t $IMAGE Project
          docker push $IMAGE
